version: '3'
services:
  minio:
    image: minio/minio:latest
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_files:/data
    ports:
      - 9000:9000
      - 9001:9001
volumes:
  minio_files:
